template_multifriend_config:
  # friend_tag: multifriend_1 ### defaults to config name
  requires:
  - template_friend_config
# template_friend_config: ### required configs are automatically added
#   friend_tag: friend_1 ### with tag as default config name

### for this example at least the --friend-config option must be used