template_multifriend_config:
  # friend_name: multifriend_1 ### defaults to config name
  requires:
  - template_friend_config
# template_friend_config: ### required configs are automatically added
#   friend_name: friend_1 ### with name as default config name