sm_2018_mt:
  classes:
  - qqh
  - ggh
  - ff
  - ztt
  - misc
  - tt
  event_weights: training_weight
  identifier:
    channel: mt
    era: '2018'
  mapping:
    emb: ztt
    ggh: ggh
    jetfakes: ff
    qqh: qqh
    ttl: tt
    vvl: misc
    zl: misc
  model:
    cut_fraction: 0.1
    early_stopping: 50
    epochs: 100000
    eventsPerClassAndBatch: 100
    name: smhtt_dropout_tanh_GPU
    preprocessing: standard_scaler
    save_best_only: true
    seed: 1234
    steps_per_epoch: 1000
    train_test_split: 0.75
  processes:
  - ttl
  - vvl
  - zl
  - ggh
  - qqh
  - emb
  - jetfakes
  processes_config: ml_configs/example_configs/processes
  variables:
  - pt_1
  - pt_2
  - m_vis
  - njets
  - nbtag
  - jpt_1
  - jpt_2
  - jeta_1
  - jeta_2
  - m_fastmtt
  - pt_vis
  - mjj
  - deltaR_ditaupair
  - pt_tt
