name: Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code_formatting:
    runs-on: ubuntu-24.04
    container:
      image: tvoigtlaender/kingmaker_standalone:V1.5
      options: --user 0
    steps:
      - name: Clone project
        uses: actions/checkout@v4
      - name: Run all formatting checks
        run: |
          git config --global --add safe.directory '*'
          bash ./checks/python-formatting.sh
