name: Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python_format:
    runs-on: ubuntu-24.04
    container:
      image: rootproject/root:6.32.00-ubuntu24.04
      options: --user 0 # run as root

    steps:
      - uses: actions/checkout@v3

      - name: apt update
        run: apt-get -y update

      - name: Install missing software
        run: apt-get install -y git python3-pip python3-venv

      - name: Create venv
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          python3 -m venv venv
          source venv/bin/activate
          pip install black==24.4.2

      - name: Check Python formatting
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          source venv/bin/activate
          bash scripts/python-formatting.sh
